name: teknofest
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  fluttertoast: ^8.2.2
  provider: ^6.1.1
  path_provider: ^2.1.2
  uuid: ^4.2.1
  google_mlkit_text_recognition: ^0.12.0
  flutter_tts: ^3.8.2
  flutter_markdown: ^0.6.18
  speech_to_text: 7.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
